apiVersion: v1
kind: Service
metadata:
  name: CHANGEME
  namespace: default
  labels:
    app: CHANGEME
spec:
  selector:
    app: CHANGEME
  type: ClusterIP
  ports:
  - name: server
    port: 80
    targetPort: server
    protocol: TCP

