package main

import (
	"fmt"
	"github.com/snarlysodboxer/k8s-spec/kctl"
	"github.com/snarlysodboxer/k8s-spec/spec"
)

type CustomKubectl struct {
	kctl.Kubectl
}

func (customKubectl *CustomKubectl) Apply(specGroup *spec.SpecGroup) error {
	fmt.Println("Custom Apply")
	return nil
}

type CustomSpec struct {
	spec.Spec
}

func (customSpec *CustomSpec) Render() (string, error) {
	fmt.Println("Custom Render")
	rendered, err := customSpec.Spec.Render()
	if err != nil {
		panic(err)
	}
	customSpec.Rendered = []byte(fmt.Sprintf("#### Auto generated by k8s-spec ####\n%s#### Auto generated by k8s-spec ####\n", rendered))
	return string(customSpec.Rendered), nil
}

func main() {
	// Create SpecGroup
	specGroup := &spec.SpecGroup{}

	// Setup Spec
	deploymentSpec := &CustomSpec{spec.Spec{}}
	specGroup.AddSpec(deploymentSpec)
	deploymentSpec.ReadTemplateFile("./example-deployment.yml")

	// Built-in Replacer
	deploymentSpec.AddReplacer(spec.NewMetadataNameReplacer("CHANGEME", "my-app"))

	// Render Spec
	rendered, err := deploymentSpec.Render()
	if err != nil {
		panic(err)
	}
	fmt.Printf("Rendered the following spec:\n\n%s\n", rendered)

	// Apply SpecGroup to k8s
	customKubectl := &CustomKubectl{kctl.Kubectl{}}
	err = customKubectl.Apply(specGroup)
	if err != nil {
		panic(err)
	}
}
